### PR TITLE
Tweaked damage indicators depending on incoming damage

### PR DESCRIPTION
**Pull request by mikeparker**
Previously, when you got hit by anything, a damage indicator flashed up on screen with a set visibility and a set fade time:

```
Animate HudDamageIndicator DmgColorRight        "255 88 0 200"  Linear 0.0 0.0
Animate HudDamageIndicator DmgColorRight        "255 0 0 200"   Linear 0.0 0.3
Animate HudDamageIndicator DmgColorRight        "255 0 0 0" Deaccel 0.3 0.5
```

I've now added a "weak hit" and a "strong hit", which flash slightly less/more strongly (less/more alpha) and for less/more time, based on how much damage you took.

Weak - less than 30 dmg
    Animate HudDamageIndicator DmgColorRight        "255 88 0 150"  Linear 0.0 0.0
    Animate HudDamageIndicator DmgColorRight        "255 0 0 150"   Linear 0.0 0.2
    Animate HudDamageIndicator DmgColorRight        "255 0 0 0" Deaccel 0.2 0.3

Medium - between 30 and 60 dmg
    Animate HudDamageIndicator DmgColorRight        "255 88 0 200"  Linear 0.0 0.0
    Animate HudDamageIndicator DmgColorRight        "255 0 0 200"   Linear 0.0 0.3
    Animate HudDamageIndicator DmgColorRight        "255 0 0 0" Deaccel 0.3 0.5

Strong - above 60 dmg
    Animate HudDamageIndicator DmgColorRight        "255 88 0 255"  Linear 0.0 0.0
    Animate HudDamageIndicator DmgColorRight        "255 0 0 200"   Linear 0.0 0.4
    Animate HudDamageIndicator DmgColorRight        "255 0 0 0" Deaccel 0.4 0.7

This requires the updated HudAnimations.txt also.

This means when you get shot you can tell to some extent how much damage you took purely based on the damage indicator. I did a "best guess" at colours, times and damage amounts, but it could do with some testing really.

### CODE REVIEW

**Comment by mikeparker** [comment]
Ping @squeek502 for thoughts

**Comment by squeek502** [comment]
How were you testing this? Is the difference apparent? I can't really seem to tell the different levels apart.

**Comment by mikeparker** [comment]
Just pipetrapping myself. One pipe vaguely nearby flashes up very briefly, one pipe standing on top of it flashes up with the old duration, then 2-3 pipes flashes up for longer. It's largely the timing thats different rather than any sizing or colour / alpha differences. We could definitely do more to make them more different. Make sure you've got the associated file on the basemod branch, i think i committed it.

**Comment by squeek502** [comment]
:+1:, may as well just merge this.

**Pull request merged**
