### PR TITLE
Lua: Continuation of #240

### PR DESCRIPTION
**Pull request by YoYo178**
- Added `player:SetFortPoints( int )`, Sets the player's fort points to a specified value.

### Some of the additions below need more testing

- Continuation of #240 
    - `buildable:IsBuilt()` Boolean, returns true if the buildable is built.
    - `buildable:Detonate()` Detonates the buildable. `-- NEEDS MORE TESTING` `doesn't leave gibs, and even the explosion isn't visible`
    - `buildable:RemoveQuietly()` Removes the buildable quietly.
    - `buildable:IsSabotaged()` Boolean, returns true if the buildable is sabotaged
    - `buildable:IsMaliciouslySabotaged()` Boolean, returns true if the buildable is maliciously sabotaged.
    - `buildable:GetSaboteur()` Returns the player who sabotaged the buildable.
    - `buildable:Sabotage( player )` Sabotages the buildable. `-- NEEDS MORE TESTING` `sg behaves weirdly, doesn't change team and starts "teamkilling" the player`
    - `buildable:MaliciouslySabotage( player )` Maliciously sabotages the buildable `-- NEEDS MORE TESTING` `sg behaves weirdly, doesn't change team and starts "teamkilling" the player`
    - `buildable:RemoveSaboteur( bool )` Removes the saboteur from the buildable, passing a Boolean specifies if the notification should be suppressed or not. `-- NEEDS MORE TESTING` `sg sometimes still continues to "teamkill" the player for a while even after removing saboteur`
    - `buildabe:CanSabotage()` Boolean, returns true if the buildable can be sabotaged.
    
some random changes :P
(edit - created a function for `builable:SetSaboteur()` yet forgot to define it in `ff_lualib_buildables`, my bad)

### CODE REVIEW

**Comment by arenaconspiracy** [comment]
what's the difference between a sabotage and a malicious sabotage? i don't get it, isn't there just one kind of sabotage?

**Comment by YoYo178** [comment]
> what's the difference between a sabotage and a malicious sabotage? i don't get it, isn't there just one kind of sabotage?

i am confused between both of them but i'm sure, that 1 of them is when you set the sabotage (you know the bar that appears)
and the other is when you actually sabotage the sentry (it switches teams and starts killing them then dies)

**Comment by fakhrraa** [comment]
"Working with <a href="mcheights.com">mcheights</a> Construction was a pleasure. They are reliable, skilled, and deliver outstanding results."

**Comment by mclodges00** [comment]
"The ambience at <a href="mclodges.com">mclodges</a> is simply delightful."

**Comment by JessyJanifer02** [comment]
"Exploring the world is easier with <a href="mcgrouppk">mcgrouppk</a> PK's expert travel arrangements."

**Comment by saimmahi** [comment]
"My wallet and my lungs are thanking me for switching to <a href="sprkvapors.com">sprkvapors</a>."

**Comment by abiharani** [comment]
"Including <a href="https://mcgrains.com/cafe-804">cafe 804 jhang</a> in the name gives it a strong local identity, which can resonate with the community and attract locals looking for a place that feels like home."

**Pull request closed without merging**
