### PR TITLE
Enable hud_deathnotice_highlightself by default and improve it a bit

### LINKED ISSUE #293: Default hud_deathnotice_highlightself to 1
Would be a lot more useful for newbies imo.

### PR DESCRIPTION
**Pull request by squeek502**
Closes #293 

Looks like this:

ff_2fort0006_cr

### CODE REVIEW

**Comment by squeek502** [comment]
This will almost certainly conflict with #288 (kill assists), so I'll wait to merge it until that gets merged. Any thoughts in the meantime, @AfterShockFF?

**Comment by AfterShockFF** [comment]
Looks good to me :+1:

**Comment by AfterShockFF** [comment]
@squeek502 it doesnt appear to conflict. I've merged the kill assists PRs. Can you check this is all good to go and merge the two PRs?

**Comment by squeek502** [comment]
If it doesn't conflict, it should be good to go.

**Pull request merged**
