### PR TITLE
Fix holding +attack2 disallowing certain weapons from firing

### LINKED ISSUE #320: Melee weapons can't be used when +attack2 is held
Really weird!

### PR DESCRIPTION
**Pull request by squeek502**
- Affected all weapons without clips (melee, autorifle, etc)

Closes #320

### CODE REVIEW

**Comment by AfterShockFF** [comment]
This doesnt stop sniper zoom working, right?

**Comment by squeek502** [comment]
Good catch, it doesn't affect sniper zoom, but it will affect buildable 'weapons'. Will fix.

**Comment by squeek502** [comment]
Actually, nevermind--nothing in FF actually uses ::SecondaryAttack. I'll cleanup the files that implement empty ::SecondaryAttack functions for clarity.

**Comment by squeek502** [comment]
Okay, should be ready to merge now.

**Pull request merged**
