### PR TITLE
[WIP] Readme

### PR DESCRIPTION
**Pull request by squeek502**
I kind of deviated from [Dexter's instructions](http://forums.fortress-forever.com/showthread.php?t=24479) a bit, leaning more towards the order of the original Microsoft guide. I'm not sure if my changes break things or not. I'll see if I can try following the guide in a clean environment sometime.

You can preview the parsed readme here: 
- https://github.com/fortressforever/fortressforever/blob/misc/readme/README.md

TODO:
- [x] Info about the post build script and where the built .dll's are
- [x] Guide to debugging (locating/loading mdmps, attaching to hl2.exe, etc)
- [ ] Linux server compile instructions?
- [ ] Code formatting guide?
- [ ] Contributing section?
- [ ] Developer workflow briefing?

### CODE REVIEW

**Comment by squeek502** [comment]
Tested in a Windows 7 64 bit VM and confirmed that the instructions are accurate/working.

**Comment by mikeparker** [comment]
Looks good so far. I wonder if making some of the design doc public would make sense?

**Comment by squeek502** [comment]
Yeah, not sure what all should be in the readme. I feel like that's indicative of an issue we're going to run into a lot during this transition, because so much discussion is gated behind the beta/dev forums and I'm not really sure how we want to handle that.

**Comment by squeek502** [comment]
Going to merge this. We can add to it as needed.

**Pull request merged**
