### PR TITLE
Delete 2003 files, no-one uses 2003 any more and one less thing to maint...

### PR DESCRIPTION
**Pull request by mikeparker**
...ain

### CODE REVIEW

**Comment by squeek502** [comment]
I thought I remember Linux builds using the 2003 projects in some way.

**Comment by mikeparker** [comment]
oh :( Any way we can get them to use 2005? Would be great to have one set of files to maintain.

**Comment by squeek502** [comment]
Maybe? There's a lot about Linux that we probably need to re-figure out.

See: https://github.com/fortressforever/fortressforever/blob/beta/linux_ff/Makefile#L14

**Comment by squeek502** [comment]
:+1: with my monkeying.

Linux is a lost cause for the moment. Can't do anything unless Valve gives us some binaries to work with.

**Pull request merged**
