### PR TITLE
Changes the way the spies name is displayed when disguised

### LINKED ISSUE #368: Spy disguise name choice
From Discord:

> Have you considered adding the name for the person when disguised, so they know who to avoid.

me: 

> havent considered that about spy, would make sense

> hm, actually looking at the code the name shown could possibly be different between players
so that would need to change too

> it kind of does things in a silly way, could definitely be improved
if there's a player that is the class you're disguised as on the team, then the name shown is always the first match found, if there's no player with the class then it chooses a random player on that team
not very spy-friendly since it doesn't randomly pick between multiple players with the same class

Relevant code:
https://github.com/fortressforever/fortressforever/blob/e7b488a008cb79b92be4a4efdea42899e8f7d1e8/cl_dll/ff/ff_hud_crosshairinfo.cpp#L390-L442

### PR DESCRIPTION
**Pull request by alaswell**
This is completely untested, but should resolve #368

### CODE REVIEW

**Review by squeek502 — APPROVED** [review]
Looks good.

Note: this is only part of #368--the other part would be syncing the chosen player across all clients so that each person sees the same name, which would also allow us to show the spy which person they are disguised as.

Right now the name is/will be different between each client, but syncing it would require changes to the networking tables, which would cause a 'server uses different class tables' error and force servers to update which isn't ideal since servers can be pretty slow to update these days.

**Comment by alaswell** [comment]
Yes, good point on the other part of #368 

We will have to add that in if/when the networking tables change again for something more significant.

**Comment by doublah** [comment]
How does this look from spectator? Is it changed there?

**Comment by squeek502** [comment]
Do you know if crosshairinfo shows while spectacting? I would think this stops it from showing:

https://github.com/fortressforever/fortressforever/blob/28b1c139647f2a68baa03f4eadd4a0eed708ed0f/cl_dll/ff/ff_hud_crosshairinfo.cpp#L143-L144

**Pull request merged**
