### PR TITLE
Add various Lua improvements that aid in moving Collection to Lua

### PR DESCRIPTION
**Pull request by squeek502**
Some misc functions useful for fortressforever/fortressforever-scripts#27

### CODE REVIEW

**Comment by DexterHaslem** [comment]
yowza, is that all the commits for this issue? or anything else you got in the pipeline

**Comment by squeek502** [comment]
That should be it.

**Comment by DexterHaslem** [comment]
cool, seems pretty straightforward. cant wait to see what people break w/ GlobalEntityList

**Comment by AfterShockFF** [comment]
:+1:

**Pull request merged**
