### PR TITLE
Reduce skim - bhop_cap_hard reduced from 2.0 to 1.9

### PR DESCRIPTION
**Pull request by mikeparker**
This reduces the skim after a conc slightly. This means after conc skim 1 they are travelling at 684 speed rather than 720. This is actually 171% of movement speed rather than 190% due to the 0.9 degen multiplier but still a fair bit higher than TFC which nerfs you back to 100% speed after a conc.

### CODE REVIEW

**Comment by squeek502** [comment]
Would be good to clean up the #defines/cvars here, as the "degen" setting does absolutely nothing except obscure the real cap.

Would be good to have a setting for the cap and a setting for the result of the cap (meaning if the cap was set to 1.9 and the result was set to 1.2, then if you jump while going >= 190% speed, you get set to 120% speed), just to keep our options open.

**Comment by AdamWillden** [comment]
Hmm, sorry I copied the definitions I think that was one of my first changes to game code (or maybe I'm just a doofus), least I put a note! :)

What is that degen doing exactly?

**Comment by squeek502** [comment]
The degen is an artifact from a previous implementation, before it was a _true_ hard cap.

**Comment by mikeparker** [comment]
Done - i've removed the weird degen variable and adjusted the hard cap accordingly. I've added a hard cap result variable which is the same as the cap itself right now.

**Comment by squeek502** [comment]
Nice. How do we want to handle things like this which might need value tweaking after its merged?

:+1: for testing this, at least.

**Comment by mikeparker** [comment]
If we want to tweak a feature after it's merged we should definitely push changes to the same branch, then we decide to rebuild a beta / release without particular features we can just not include that branch. The question is whether to take the original branch out or not. To do it "properly", we should (take the old branch out) then put the new branch in, instead.

**Pull request merged**
